#!/usr/bin/env python
# coding: utf-8

# # CSE110 Lab Assignment 1 (Branching)
# 
# This assignment is to guide you to solve basic programming problems in Python. Since this is the first assignment, the first problem is solved for you with explanations. The second problem is partially solved to help you. Please go through them and try to understand each statment. If you can understand the problems and the solutions done for you, you can try to solve the rest of the tasks by yourself. 
# 
# **<font color='red'>Please maintain variable naming conventions for all the tasks.</font>**\
# <font color='red'>When you run your code, please make sure your outputs exactly match the sample outputs for each of the sample inputs given. Check if your code works for other valid inputs not given in the samples.</font>
# 
# ## Write the Python code for the following problems:
# 

# ### Task 1
# 
# Write the Python code of a program that reads two numbers from the user, and prints their sum, product, and difference.
# 
# ==========================================================
# 
# *Hint: subtract the second number from the first one*
# 
# ==========================================================
# 
# **Example 1:**
# 
# **Sample Input:**\
#  4\
#  5
# 
# **Sample Output:**\
# Sum = 9\
# Product = 20\
# Difference = -1
# 
# ==========================================================
# 
# **Example 2:**
# 
# **Sample Input:**\
#  30\
#  2
# 
# **Sample Output:**\
# Sum = 32\
# Product = 60\
# Difference = 28
# 
# ==========================================================
# 
# For your explanation, the first question's code is done below. Try relating the block of code with the lessons you have learned and try to understand the significance of each line. You're most welcome to play around with the code. This will strengthen your understanding.
# 

# In[ ]:


# First, we take 2 numbers as input from the user
# Read 2 numbers as input from the user means taking 2 numbers as input from the user using the input function
var_1 = input('Please enter the first number: ')
var_2 = input('Please enter the second number: ')

#Since input() function converts everything to String,
#for performing any kind of mathematical operation we need to convert them to int.
#For this conversion, we need to use the int() function


#But at first, we may clarify whether the inputs are actually Strings or not. 
print(type(var_1))
print(type(var_2))


#Then we convert the Strings to integer using the int() function
var_3 = int(var_1)
var_4 = int(var_2)

#===============================================================
#Input taking and conversion can be done in a single line as shown below
#var_1 = int(input('Please enter the first number: '))
#var_2 = int(input('Please enter the second number: '))

#===============================================================

#We may then perform Addition
total = var_3 + var_4

#Multiplication 
product = var_3 * var_4

#Substraction 
difference = var_3 - var_4

#And then print all the calculated results
print("Sum =", total)
print("Product =", product)
print("Difference =", difference)


# ### Task 2
# 
# Write the Python code of a program that reads the radius of a circle and prints its circumference and area.
# 
# ==========================================================
# 
# *hint(1): we may import math and then use **math.pi** for getting the value of pi.\
# For details, we can read from https://docs.python.org/3/library/math.html*
# 
# *hint(2): we can import math and use the math function for making squares with math.pow(number, power) or we can simply use the power operator. For example:  S**2.*
# 
# ==========================================================
# 
# **Example 1:**
# 
# **Sample Input:**\
# 4
# 
# **Sample Output:**\
# Area is 50.26548245743669\
# Circumference is 25.132741228718345
# 
# ==========================================================
# 
# **Example 2:**
# 
# **Sample Input:**\
# 3.5
# 
# **Sample Output:**\
# Area is 38.48451000647496\
# Circumference is 21.991148575128552
# 
# ==========================================================
# 
# For your understanding, the the first part of the question(area calculation) is done below.

# In[ ]:


import math 

# taking input from the user, then converting it to float
# since radius can be a floating point value

radius  = float(input("Please enter the radius value:")) 

# squares can be made using these 3 ways, as give in hints
# all 3 ways generates the same result for area

area = math.pi * radius ** 2 
print("Area is:", area)

area = math.pi * math.pow(radius, 2)
print("Area is:", area)

area = math.pi * radius * radius
print("Area is:", area)

#==============================================================
# TODO
# calculate circumference

#==============================================================


# ### Task 3
# 
# Write the Python code of a program that reads two numbers from the user. The program should then print "First is greater" if the first number is greater, "Second is greater" if the second number is greater, and "The numbers are equal" otherwise.
# 
# ==========================================================
# 
# **Sample Input 1:**\
# 7\
# 3
# 
# **Sample Output 1:**\
# First is greater
# 
# ==========================================================
# 
# **Sample Input 2:**\
# -33\
# -3
# 
# **Sample Output 2:**\
# Second is greater
# 
# ==========================================================
# 
# **Sample Input 1:**\
# 11\
# 11
# 
# **Sample Output 1:**\
# The numbers are equal
# 

# In[ ]:


var_1= int(input("Please enter your first number: "))
var_2= int(input("Please enter your second number: "))

if var_1>var_2:
  print("First is greater")
elif var_1<var_2:
  print("Second is greater")
else:
  print("The numbers are equal")  


# ### Task 4
# 
# Write the Python code of a program that reads two numbers, subtracts the smaller number from the larger one, and prints the result.
# 
# *Hint: First, we may check which number is greater*
# 
# ==========================================================
# 
# **Sample Input 1:**\
# -40\
# -4
# 
# **Sample Output 1:**\
# 36
# 
# **Explanation:** -4 > -40 so -4 - (-40) = -4 + 40 = 36
# 
# ==========================================================
# 
# **Sample Input 2:**\
# 6\
# 2
# 
# **Sample Output 2:**\
# 4
# 
# ==========================================================
# 
# 
# **Sample Input 3:**\
# 5\
# 5
# 
# **Sample Output 3:**\
# 0
# 

# In[1]:


var_1= int(input("Enter 1st number: "))
var_2= int(input("Enter 2nd number: "))
if var_1>var_2:
   print(var_1-var_2)
else:
   print(var_2-var_1)  


# ### Task 5
# 
# Write the Python code of a program that reads a number, and prints "The number is even" or "The number is odd", depending on whether the number is even or odd. 
# 
# *hint(1): we may use the modulus (%) operator to check for even or odd*
# 
# *hint(2): we can consider the number to be an integer* 
# 
# ==========================================================
# 
# **Sample Input 1:**\
# 7
# 
# **Sample Output 1:**\
# The number is odd
# 
# ==========================================================
# 
# **Sample Input 2:**\
# 10
# 
# **Sample Output 2:**\
# The number is even
# 
# ==========================================================
# 
# **Sample Input 3:**\
# -44
# 
# **Sample Output 3:**\
# The number is even
# 

# In[ ]:


var= int(input("enter a number: "))
if(var % 2== 0): 
  print("The number is even")
else:
  print("The number is odd ")


# ### Task 6
# 
# Write the Python code of a program that reads an integer as input from the user, and prints the integer if it is a multiple of **2 OR 5** and prints "Not a multiple of 2 OR 5" otherwise.
# 
# For example, 2, 4, 5, 6, 8, 10, 12, 14, 15, 16, 18, 20, 22 … i.e. this includes multiples of 2 only, multiples of 5 only and multiples of 2 and 5 both.
# 
# ==========================================================
# 
# *hint(1): we may use the modulus (%) operator for checking the divisibility*
# 
# *hint(2): we can consider the number to be an integer* 
# 
# ==========================================================
# 
# **Sample Input 1:**\
# 5
# 
# **Sample Output 1:**\
# 5
# 
# ==========================================================
# 
# **Sample Input 2:**\
# 10
# 
# **Sample Output 2:**\
# 10
# 
# ==========================================================
# 
# **Sample Input 3:**\
# 3
# 
# **Sample Output 3:**\
# Not a multiple of 2 OR 5
# 

# In[ ]:


var=int(input("enter a number: "))
if(var%2==0 or var%5==0 ):
  print(var)
  
else:
  print("Not a multiple of 2 or 5")    


# ### Task 7
# Write the Python code of a program that reads an integer, and prints the integer  it is a multiple of **either 2 or 5 but not both.** If the number is a multiple of 2 and 5 both, then print "Multiple of 2 and 5 both". For all other numbers, the program prints "Not a multiple we want".
# 
# For example, 2, 4, 5, 6, 8, 12, 14, 15, 16, 18, 22 … i.e. this includes multiples of 2 only and multiples of 5 only, NOT multiples of 2 and 5 both or other numbers.
# 
# ==========================================================
# 
# *hint(1): we may use the modulus (%) operator for checking the divisibility*
# 
# *hint(2): we can consider the number to be an integer* 
# 
# ==========================================================
# 
# **Sample Input 1:**\
# 6
# 
# **Sample Output 1:**\
# 6
# 
# ==========================================================
# 
# **Sample Input 2:**\
# 15
# 
# **Sample Output 2:**\
# 15
# 
# ==========================================================
# 
# **Sample Input 3:**\
# 10
# 
# **Sample Output 3:**\
# Multiple of 2 and 5 both
# 
# ==========================================================
# 
# **Sample Input 4:**\
# 17
# 
# **Sample Output 4:**\
# Not a multiple we want

# In[ ]:


var=int(input("enter a number:"))
if(var%2==0 and var%5==0):
  print("Multiple of both 2 and 5")
elif(var%2==0 or var%5==0):
  print(var)
else:
  print("Not a multiple we want")


# ### Task 8
# Write the Python code of a program that reads an integer, and prints the integer if it is a multiple of **2 AND 5** and prints "Not multiple of 2 and 5 both" otherwise.
# 
# ==========================================================
# 
# For example, 10, 20, 30, 40, 50 … i.e. this only includes numbers which are multiples of both 2 and 5.
# 
# *hint(1): we may use the modulus (%) operator for checking the divisibility*
# 
# *hint(2): we can consider the number to be an integer* 
# 
# ==========================================================
# 
# **Sample Input 1:**\
# 30
# 
# **Sample Output 1:**\
# 30
# 
# ==========================================================
# 
# **Sample Input 2:**\
# 15
# 
# **Sample Output 2:**\
# Not multiple of 2 and 5 both
# 
# 
# ==========================================================
# 
# **Sample Input 3:**\
# 6
# 
# **Sample Output 3:**\
# Not multiple of 2 and 5 both

# In[ ]:


var=int(input("enter a number: "))
if(var%2==0 and var%5==0):
  print(var)
else:
  print("Not multiple of 2 and 5 both")  


# ### Task 9
# Write the Python code of a program that finds the number of hours, minutes, and seconds in a **given number of seconds.** The number of seconds is taken as input from the user.
# 
# ==========================================================
# 
# *hint(1): we may consider our user input to be an integer value and use // and % operators to solve the problem* 
# 
# *hint(2): 1 hour = 60 mins = 3600 seconds* and *1 min = 60 seconds* 
# 
# ==========================================================
# 
# **Sample Input 1:**\
# 10000
# 
# **Sample Output 1:**\
# Hours: 2  Minutes: 46  Seconds: 40
# 
# **Explanation:**\
# 10000 seconds = 10000 // 3600 = 2 hours and 10000 % 3600 = 2800 seconds.\
# Then again, 2800 // 60 = 46 minutes and 2800 % 60 = 40 seconds.\
# And hence we have arrived at our answer.
# 
# ==========================================================
# 
# **Sample Input 2:**\
# 500
# 
# **Sample Output 2:**\
# Hours: 0  Minutes: 8  Seconds: 20
# 

# In[1]:


var= int(input("Enter your number: "))

hours= var//3600;
print("Hours:" ,hours)

minutes= var%3600;
m=minutes//60;
print("Minutes:", m)

seconds= minutes%60;
print("Seconds:",seconds)


# ### Task 10
# 
# Write a Python program to compute and display a person’s weekly salary as determined by the following conditions:
# 
# * If the hours worked is less than or equal to 40, then the person receives Tk 200 per hour.
# * If the hours worked is greater than 40, then the person receives Tk 8000 plus Tk 300 for each hour worked over 40 hours.
# 
# The program should request the hours worked as an input from the user and display the salary as output. You need to make sure that user input is valid. For example, a person cannot work for -5 hours or more than 168 hours in a week. So, the valid hours range is 0 to 168. For invalid hours, print outputs as given in the samples below.
# 
# ==========================================================
# 
# *Hint: you can consider the hour (user input) to be an integer* 
# 
# ==========================================================
# 
# **Sample Input 1:**\
# 100
# 
# **Sample Output 1:**\
# 26000
# 
# **Explanation:** Since, the number of hours worked is 100 > 40, therefore salary = 8000 + (100 - 40) * 300 = 26000.
# 
# ==========================================================
# 
# **Sample Input 2:**\
# 30
# 
# **Sample Output 2:**\
# 6000
# 
# **Explanation:** Since, the number of hours worked is 30 < 40, therefore salary = 30 * 200 = 6000.
# 
# ==========================================================
# 
# **Sample Input 3:**\
# -30
# 
# **Sample Output 3:**\
# Hour cannot be negative
# 
# ==========================================================
# 
# **Sample Input 4:**\
# 170
# 
# **Sample Output 4:**\
# Impossible to work more than 168 hours weekly

# In[ ]:


var=int(input("enter your hour: "))

if var>168:
    print("Impossible to work more than 168 hours weekly")

elif var<0:
    print("Hour cannot be negative")

elif var<=40:
    print("Salary:" ,var*200)
elif var>40:
    print("Salary:", 8000+(var-40)*300)


# ### Task 11
# Suppose the following expressions are used to calculate the values of L for different values of S:
# 
# $L =  3000-125S^2$ 
# if     $S<100$
# 
# $ L =  \frac{12000}{4+S^2/14900}$
# if     $S\geq100$
# 
# Write the Python code of a program that reads a value of S and then calculates the value of L.
# 
# ==========================================================
# 
# *hint(1): you can import math and use math function for making squares with math.pow(number, power) or you can simply write S ** 2.*
# 
# *hint(2): the value of S(user input) will be an integer* 
# 
# ==========================================================
# 
# **Sample Input 1:**\
# 120
# 
# **Sample Output 1:**\
# 2416.2162162162163
# 
# **Explanation:** Since S (user input) given here is 120 >= 100, so L = 12000 / (4 + (120 * 120)/14900) = 2416.2162162162163
# 
# ==========================================================
# 
# **Sample Input 2:**\
# 3
# 
# **Sample Output 2:**\
# 1875
# 
# **Explanation:** Since S (user input) given here is 3 < 100, so L = 3000 - 125 * 3 * 3 = 1875
# 

# In[ ]:


var=int(input("Enter your number: "))

if var<100:
    L=3000-125*var**2
    print(L)

elif var>=100:
    L=12000/(4+(var**2)/14900)
    print(L)


# ### Task 12
# 
# Write a Python program that takes an hour from the user as input and tells it is time for which meal.
# 
# •	The user will input the number in a 24-hour format. So, 14 means 2 pm, 3 means 3 am, 18 means 6 pm, etc.\
# •	Valid inputs are 0 to 23. Inputs less than 0 or more than 23 are invalid in 24-hour clock.\
# •	Assume, input will be whole numbers. For example, 3.5 will NOT be given as input.
# 
# ==========================================================
# 
# **Input range: Message to be printed**\
# 4 to 6: Breakfast\
# 12 to 13: Lunch\
# 16 to 17: Snacks\
# 19 to 20: Dinner\
# For all other valid inputs, say "Patience is a virtue"\
# For all other invalid inputs, say "Wrong time"
# 
# ==========================================================
# 
# For example,\
# If the user enters 4, your program should print the message "Breakfast".\
# If the user enters 5, your program should print the message "Breakfast".\
# If the user enters 6, your program should print the message "Breakfast".\
# If the user enters 0, your program should print the message "Patience is a virtue".\
# If the user enters 1, your program should print the message "Patience is a virtue".\
# If the user enters 18, your program should print the message "Patience is a virtue".\
# If the user enters 23, your program should print the message "Patience is a virtue".\
# If the user enters 24, your program should print the message "Wrong Time".\
# If the user enters -1, your program should print the message "Wrong Time".\
# If the user enters 27, your program should print the message "Wrong time".
# 
# ==========================================================
# 
# Hints: You can use nested conditionals (if-else) or chained conditions (if-elif-else) to solve this problem.
# 
# 

# In[ ]:


var=int(input("Enter your hour: "))

if(var>=4 and var<=6):
    print("Breakfast")

elif(var==12 or var==13):
    print("Lunch")
elif(var==16 or var==17):
    print("Snacks")
elif(var==19 or var==20):
    print("Dinner")

elif(var>=0 and var<=23):
    print("Patience is a virtue")
else:
    print("Wrong time")


# ### Task 13
# 
# Write the Python code of a program that reads a student’s mark for a single subject, and prints out the corresponding grade for that mark. The mark ranges and corresponding grades are shown in the table below. You need to make sure that the mark is valid. For example, a student cannot receive -5 or 110 marks. So, the valid marks range is 0 to 100.
# 
# *hint(1): you can consider the number to be an integer* 
# 
# *hint(2): this problem can be solved in two ways: top-down (starts from A) and bottom-up (starts from F)*
# 
# 
# | Marks | Grade|
# | --- | --- | 
# |90 or above| A |
# |  |  | 
# |80-89| B |
# |  |  | 
# |70-79| C |
# |  |  | 
# |60-69| D |
# |  |  | 
# |50-59| E |
# |  |  | 
# |Below 50| F |
# |  |  |
# 

# In[ ]:


var=int(input("Enter your marks: "))

if(var>=90 and var<=100):
    print("A")
elif(var>=80 and var<=89):
    print("B")
elif(var>=70 and var<=79):
    print("C")
elif(var>=60 and var<=69):
    print("D")
elif(var>=50 and var<=59):
    print("E")
elif(var>=0 and var<=49):
    print("F")
else:
    print("Invalid"


# ### Task 14
# 
# You are designing a robot that can calculate the temperature and guess the season. Write a Python program that takes a number as input, representing the temperature in degrees Fahrenheit, and converts it into degrees Celsius, and then prints the season based on the following table:
# 
# 
# | Temperature (degrees Celsius) | Season|
# | --- | --- | 
# |Less than 20 degrees| Winter |
# |  |  | 
# |Between 20 degrees and 25 degrees (inclusive)| Autumn |
# |  |  | 
# |Greater than 25 degrees and less than 30 degrees| Spring |
# |  |  | 
# |Greater than or equal to 30 degrees| Summer |
# |  |  | 
# 
# 
# Use the following formula to convert the temperature:\
# (degrees Celsius) = ((degrees Fahrenheit) - 32) * 0.56
# 
# ==========================================================
# 
# **Sample Input 1:**\
# 82
# 
# **Sample Output 1:**\
# 28 degrees C\
# Spring
# 
# **Explanation:** The temperature in Celsius is (82 - 32) * 0.56 = 28 degrees, which is printed. This is between 25 and 30 degrees, so “Spring” is printed after that.
# 
# ==========================================================
# 
# **Sample Input 2:**\
# 32
# 
# **Sample Output 2:**\
# 0 degrees C\
# Winter
# 
# **Explanation:** The temperature in Celsius is (32 - 32) * 0.56 = 0 degrees, which is printed. This is less than 20 degrees, so “Winter” is printed after that.
# 
# ==========================================================
# 
# **Sample Input 3:**\
# 76
# 
# **Sample Output 3:**\
# 24.64 degrees C\
# Autumn
# 
# **Explanation:** The temperature in Celsius is (76 - 32) * 0.56 = 24.64 degrees, which is printed. This is between 20 degrees and 25 degrees (inclusive), so “Autumn” is printed after that.
# 
# ==========================================================
# 
# **Sample Input 4:**\
# 77
# 
# **Sample Output 3:**\
# 25.2 degrees C\
# Spring
# 
# **Explanation:** The temperature in Celsius is (77 - 32) * 0.56 = 25.2 degrees, which is printed. This is greater than 25 degrees and less than 30 degrees, so “Spring” is printed after that.
# 

# In[ ]:


var=int(input("Enter your number: "))

Celsius=((var)-32)*0.56

if Celsius<20:
    print("Winter")
elif Celsius>=20 and Celsius<=25:
    print("Autumn")
elif Celsius>25 and Celsius<30:
    print("Spring")
elif Celsius>=30:
    print("Summer")


# ### Task 15
# Suppose, your friend is building an automated car called “Besla”. He needs to fix the programming of the car so that it runs at a proper speed. Now, write a python program that takes 2 inputs (distance in meters and time in seconds). The program should then print the velocity in kilometers per hour of that car. Also, it should print whether the car is working properly based on the following chart.
# 
# |Velocity|Information to be printed|
# |------|------|
# |Less than 60 km/h  |Too slow. Needs more changes.
# |Between 60 km/h to 90 km/h |Velocity is okay. The car is ready!
# |Greater than 90 km/h|Too fast. Only a few changes should suffice. 
# 
# ==========================================
# 
# **Sample Input 1:**\
# 160000\
# 7200
# 
# 
# **Sample Output 1:**\
# 80.0 km/h\
# Velocity is okay. The car is ready!
# 
# 
# **Explanation:** After the conversion of distance and time, the velocity is (160/2) km/h = 80 km/h. So the velocity is okay
# 
#  ==========================================
# 
# **Sample Input 2:**\
# 25400\
# 3600
# 
# 
# **Sample Output 2:**\
# 25.4 km/h\
# Too slow. Needs more changes.
# 
# **Explanation:** After the conversion of distance and time, the velocity is (25.4/1) km/h = 25.4 km/h. So the speed is too slow.

# In[ ]:


var_1=int(input("Enter distance in meters: "))
var_2=int(input("Enter time in seconds: "))

KM=var_1/1000
H=var_2/3600

Velocity=KM/H

if Velocity<60:
    print("Too slow.Needs more changes")
elif Velocity>=60 and Velocity<=90:
    print("Velocity is okay.The car is ready!")
elif Velocity>90:
    print("Too fast.Only a few changes should suffice")


# ### Task 16
# Write a python program that takes the CGPA and no of credits completed by a student and prints whether the student is eligible for a waiver and of what percentage. 
# 
# To be eligible for a waiver, a student must have completed at least 30 credits and earned a CGPA greater or equal to 3.8. If not, please print "The students is not eligible for a waiver".
# 
# **CGPA** | **Waiver percentage**
# --- | ---
# 3.80 - 3.89 | 25 percent
# 3.90 - 3.94 | 50 percent
# 3.95 - 3.99 | 75 percent
# 4.00 | 100 percent
# 
# 
# **Sample Input 1:** \
# 3.93 \
# 78 \
# 
# **Sample Output 1:**\
# The student is eligible for a waiver of 50 percent.
# 
# ================================================================================
# 
# **Sample Input 2:** \
# 3.79 \
# 24 \
# 
# **Sample Output 2:**\
# The students is not eligible for a waiver \
# 

# In[ ]:


var_1=float(input("Enter your CGPA: "))
var_2=int(input("Enter your credits: "))

if var_2>=30:

  if var_1>=3.80 and var_1<=3.89:
    print("The student is eligible for a wavier of 25 percent.")

  if var_1>=3.90 and var_1<=3.94:
      print("The student is eligible for a wavier of 50 percent.")

  if var_1>=3.95 and var_1<=3.99:
      print("The student is eligible for a wavier of 75 percent.")

  if var_1==4.00:
      print("The student is eligible for a wavier of 100 percent.")

else:
    print("The student is not eligible for a wavier.")


# ## Optional Tasks (17 - 19) [Ungraded]

# **These tasks are just for practice. No marks will be deducted for not completing them and no bonus marks will be given for solving them. Just try and practice these problems.**

# ### Task 17
# 
# Write the Python code of a program that reads an integer, and prints the integer if it is a multiple of **NEITHER 2 NOR 5.** 
# 
# For example, 1, 3, 7, 9, 11, 13, 17, 19, 21, 23, 27, 29, 31, 33, 37, 39 …
# 
# ==========================================================
# 
# *hint(1): you may use the modulus (%) operator for checking the divisibility*
# 
# *hint(2): you can consider the number to be an integer* 
# 
# 
# ==========================================================
# 
# **Sample Input 1:** \
# 3
# 
# **Sample Output 1:** \
# 3
# 
# 
# ==========================================================
# 
# 
# **Sample Input 2:** \
# 19
# 
# **Sample Output 2:** \
# 19
# 
# ==========================================================
# 
# 
# **Sample Input 3:** \
# 5
# 
# **Sample Output 3:** \
# No
# 
# ==========================================================
# 
# 
# **Sample Input 4:** \
# 12
# 
# **Sample Output 4:** \
# No
# 

# In[ ]:


var_1=int(input("enter: "))


if var_1%2==0 or var_1%5==0:
    print("no")

else:
    print(var_1)


# ### Task 18
# 
# Write the Python code of a program that reads an integer, and prints the integer if it is **NOT a multiple of 2** OR **NOT a multiple of 5.**
# 
# For example, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 17, 18, 19, 21, 22
# 
# ==========================================================
# 
# *hint(1): you may use the modulus (%) operator for checking the divisibility*
# 
# *hint(2): you can consider the number to be an integer* 
# 
# 
# ==========================================================
# 
# **Sample Input 1:** \
# 3
# 
# **Sample Output 1:** \
# 3
# 
# ==========================================================
# 
# **Sample Input 2:** \
# 15
# 
# **Sample Output 2:** \
# 15
# 
# ==========================================================
# 
# **Sample Input 3:** \
# 20
# 
# **Sample Output 3:** \
# No
# 
# ==========================================================
# 
# **Sample Input 4:** \
# 14
# 
# **Sample Output 4:** \
# 14

# In[ ]:


var_1=int(input("enter: "))


if var_1%2==0 and var_1%5==0:
    print("no")

else:
    print(var_1)


# ### Task 19
# Fiona has recently started acrylic painting and she is planning to order a few canvases and paints from an online stationery shop. The price of each 10 x 10 sized canvas is **120 tk** and the price of each 25 ml paint tube is **75 tk**. Depending on the total amount ordered from the shop, she will get some discounts. The table below shows the discount she will get on her total amount.
# 
# 
# |Total Amount (TK)|Discount (TK)|
# |------|------|
# |0 - 299|No Discount|
# |300 - 499|10|
# |500 - 749 |20|
# |750 - 999|50|
# |>= 1000|150|
# 
# Write a python program and take two inputs from the user. The first input will be the number of canvases and the second input will be the number of paint tubes ordered. Based on the price of each item, calculate the total amount that Fiona needs to pay including the discount.  
# 
#  ================================
# 
# 
# **Sample Input 1:**\
# 5\
# 8
# 
# 
# **Sample Output 1:**\
# Previous total: 1200\
# New total after discount: 1050
# 
# 
# **Explanation:** 5 * 120 + 8 * 75 = 1200 Tk was her bill without discount.  For 1200 Tk, the discount amount is 150 Tk. So, her new bill with a discount is (1200 - 150) = 1050 Tk.
# 
# ================================
# 
# **Sample Input 2:**\
# 0\
# 3
# 
# 
# **Sample Output 2:**\
# Previous total: 225\
# New total after discount: 225
# 
# 
# 
# **Explanation:** 0 * 120 + 3 * 75 = 225 Tk was her bill without discount.  For 225 Tk, the discount amount is 0 Tk. So, her new bill with a discount is (225 - 0) = 225 Tk.
# 

# In[ ]:


a = int(input("enter: "))
b = int(input("enter: "))

sum = 0

x = a * 120
y = b * 75

sum = x + y
print(sum)

if sum <=299:
    print(sum)
elif sum>=300 and sum<=499:
    print(sum-10)
elif sum<=500 and sum>=749:
    print(sum-20)
elif sum>=1000:
    print(sum-150)


# In[ ]:


#todo

